#!/bin/bash

# Requirements
# Get today's full date - DONE
# Try to open daily note
# Copy the daily notes template to appropriate path including filename if it doesn't exist

# Get todays date and day name
today=$(date '+%Y-%m-%d-%A')
year=$(date '+%Y')
month=$(date '+%m-%B')
template_path=$HOME/Documents/second_brain/templates/Daily.md
daily_path=$HOME/Documents/second_brain/daily
path=$HOME/Documents/second_brain/daily/${year}/${month}/${today}.md
sb_path=$HOME/Documents/second_brain

# Check if year and month exist for daily note
if [ ! -d "${sb_path}/${year}" ]; then
	mkdir "${sb_path}/${year}"
fi
if [ ! -d "${sb_path}/${year}/${month}" ]; then
	mkdir "${sb_path}/${year}/${month}"
fi
if [ ! -f "${path}" ]; then
	echo "Daily note not found. Attempting to make now..."
	if [ ! -d "${sb_path}" ]; then
		echo "Template not found. Looks like your vault is jacked up..."
	fi
	cp "${template_path} ${path}"
fi

nvim "${path}"
