#!/bin/bash

# bsp, float or stack (default: float)
yabai -m config layout stack

# Set all padding and gaps to 10pt (default: 0)
yabai -m config top_padding 9
yabai -m config bottom_padding 10
yabai -m config left_padding 10
yabai -m config right_padding 10
yabai -m config window_gap 10

# Ignore certain apps
yabai -m rule --add app="^System Settings$" manage=off
