#!/bin/bash

yabai -m config \
  external_bar main:36:0 \
  layout stack \
  top_padding 10 \
  bottom_padding 10 \
  left_padding 10 \
  right_padding 10

# Ignore certain apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^ZwiftAppSilicon$" manage=off

# Unique management of apps
yabai -m rule --add app="Emacs" manage=on focus=on
yabai -m rule --add app="WezTerm" manage=on focus=on
